# Generated by Django 3.2 on 2022-03-05 11:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/ddxxrzq7g/image/upload/v1646105774/pink_flowers_pskkjx.jpg', max_length=255, verbose_name='image'),
        ),
    ]
