# Generated by Django 3.2 on 2022-03-15 18:09

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, max_length=200, populate_from='title', unique=True),
        ),
    ]
